config/routes.rb
KickStarter::Application.routes.draw do

  root :to => 'projects#index'

  resources :projects do
    collection do
      get :top_hits
    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :abstract, :budget, :description, :title

  	def self.expensive 
  		self.where('budget > ?', 100)
  	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	before_filter :find_project, :only => [:edit, :update]

	def new
		@project = Project.new
	end

	def create
		#binding.pry
		@project = Project.new(params[:project])
		if @project.save
			redirect_to projects_path
		else
			redirect_to :back
		end
	end

	def index
		@count = Project.count
		 @projects = Project.all
	end

	def edit
		# @project = Project.find params[:id]
		# redirect_to edit_project_path
	end

	def update 
		
		# @project = Project.find params[:id]
		@project.update_attributes(params[:project])
		redirect_to projects_path
	end

	def destroy 
		@project = Project.find params[:id]
		@project.destroy
		redirect_to projects_path
	end

	def show
		@project = Project.find params[:id]
	end

	def top_hits 
		@projects = Project.expensive
	end

	private
		def find_project
			@project = Project.find params[:id]
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KickStarter</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project do |f|%>
	<%= f.label :name%><br>
	<%= f.text_field :title%> <br>
  <%= f.label :description%> <br>
  <%= f.text_field :description%> <br>
  <%= f.label :abstract%><br>
  <%= f.text_field :abstract%> <br>
  <%= f.label :budget%> <br>
  <%= f.text_field :budget%> <br>
  <%= f.submit button_name%> <br><br>
  <%= link_to 'Back', projects_path %> 
<%end%>

app/views/projects/edit.html.erb
<h1>Update project</h1>


<%= render 'form', button_name: 'Submit'%>

app/views/projects/index.html.erb
<h1> The no. of project is <%= @count%> </h1><br>
<h3><%= link_to 'Add New Project', new_project_path %> </h3>	<br>
<h3><%= link_to 'View top Projects', top_hits_projects_path %></h3>
<h3>
	<table border="1"> 
		<thead> 
			<th> 
				Name of project
			</th>
			<th> 
				Abstract
			</th>
			<th>action</th>
			<th></th>
			<th></th>
		</thead>
			<% @projects.each do |project|%> 
		<tbody>	
			<td> 
				<%= project.title%>
			</td>
			<td>
				<%= project.abstract %>
			</td>
			<td><%= link_to 'Edit', edit_project_path(project.id) %></td>
			<td><%= link_to 'Delete', project_path(project.id), method: 'delete' %></td>
			<td><%= link_to ' View Detail', project_path(project.id)%></td>
		</tbody>
		<%end%>
	</table>
</h3>

	 
	 

app/views/projects/new.html.erb
<h1>About your project</h1>
<%= render 'form', button_name: 'Submit'%>

app/views/projects/show.html.erb
<table border="1"> 
		<thead> 
			<th> 
				Name of project
			</th>
			<th> 
				Abstract
			</th>
			<th>Description</th>
			<th>Budget</th>
		</thead>
			
		<tbody>	
			<td> 
				<%= @project.title%>
			</td>
			<td>
				<%= @project.abstract %>
			</td>
			<td><%= @project.description %></td>
			<td>$<%= @project.budget %></td>
		</tbody>
	</table>

	 <%= link_to 'Back', projects_path %>

app/views/projects/top_hits.html.erb
<h3> Top Hits Projects</h3>

<table border="1"> 
		<thead> 
			<th> 
				Name of project
			</th>
			<th> 
				Abstract
			</th>
			<th>Description</th>
			<th>Budget</th>
		</thead>
			<% @projects.each do |project|%> 
		<tbody>	
			<td> 
				<%= project.title%>
			</td>
			<td>
				<%= project.abstract %>
			</td>
			<td> 
				<%= project.description%>
			</td>
			<td>
				<%= project.budget %>
			</td>
		</tbody>
		<%end%>
	</table>

	<%= link_to 'Back', projects_path %>